common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5  

production:
  <<: *common
  database: heroku_overwites_this
development:
  <<: *common
  database: orq
  username: orq
  host: localhost